/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ContatoDao;
import DAO.DaoFactory;
import entities.Contato;
import enums.Sexo;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.utils.LimpaTela;

/**
 *
 * @author ederc
 */
public class FrmCadastro extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastro
     */
    public FrmCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        PainelDeAbas = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        jPanelAreaCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        txtNomeRua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        txtNome = new javax.swing.JTextField();
        btnNovo = new javax.swing.JToggleButton();
        btnAlterar = new javax.swing.JToggleButton();
        lblObrigatorioNome = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        txtTel_residencial = new javax.swing.JFormattedTextField();
        txtTel_comercial = new javax.swing.JFormattedTextField();
        btnBuscaCep = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jPanelConsulta = new javax.swing.JPanel();
        jPanelAreaConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaContatos = new javax.swing.JTable();
        txtConsultaBuscar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda Java");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PainelPrincipal.setBackground(new java.awt.Color(0, 204, 204));

        jTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(0, 51, 51));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTitulo.setText("Agenda");

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelDeAbas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelDeAbasMouseClicked(evt);
            }
        });

        jPanelAreaCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAreaCadastroMouseClicked(evt);
            }
        });
        jPanelAreaCadastro.setLayout(null);

        jLabel2.setText("E-mail");
        jPanelAreaCadastro.add(jLabel2);
        jLabel2.setBounds(610, 60, 35, 16);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanelAreaCadastro.add(txtEmail);
        txtEmail.setBounds(647, 54, 290, 24);

        jLabel3.setText("Sexo");
        jPanelAreaCadastro.add(jLabel3);
        jLabel3.setBounds(840, 140, 29, 16);

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", "O" }));
        jPanelAreaCadastro.add(comboSexo);
        comboSexo.setBounds(880, 140, 63, 26);

        jLabel4.setText("Tipo Logradouro");
        jPanelAreaCadastro.add(jLabel4);
        jLabel4.setBounds(40, 140, 93, 16);

        txtLogradouro.setToolTipText("");
        txtLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogradouroActionPerformed(evt);
            }
        });
        jPanelAreaCadastro.add(txtLogradouro);
        txtLogradouro.setBounds(150, 140, 80, 24);

        txtNomeRua.setToolTipText("");
        jPanelAreaCadastro.add(txtNomeRua);
        txtNomeRua.setBounds(240, 140, 457, 24);

        jLabel5.setText("Número");
        jPanelAreaCadastro.add(jLabel5);
        jLabel5.setBounds(700, 140, 45, 16);

        jLabel6.setText("Bairro");
        jPanelAreaCadastro.add(jLabel6);
        jLabel6.setBounds(90, 180, 35, 16);

        txtBairro.setToolTipText("");
        jPanelAreaCadastro.add(txtBairro);
        txtBairro.setBounds(150, 180, 199, 24);

        jLabel7.setText("Cidade");
        jPanelAreaCadastro.add(jLabel7);
        jLabel7.setBounds(360, 180, 39, 16);

        txtCidade.setToolTipText("");
        jPanelAreaCadastro.add(txtCidade);
        txtCidade.setBounds(400, 180, 199, 24);

        jLabel8.setText("Estado");
        jPanelAreaCadastro.add(jLabel8);
        jLabel8.setBounds(610, 180, 39, 16);

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanelAreaCadastro.add(comboEstado);
        comboEstado.setBounds(660, 180, 80, 26);

        jLabel9.setText("CEP");
        jPanelAreaCadastro.add(jLabel9);
        jLabel9.setBounds(110, 100, 23, 16);

        jLabel10.setText("Tel. Res.");
        jPanelAreaCadastro.add(jLabel10);
        jLabel10.setBounds(410, 100, 56, 16);

        jLabel11.setText("Tel. Celular");
        jPanelAreaCadastro.add(jLabel11);
        jLabel11.setBounds(670, 100, 63, 16);

        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanelAreaCadastro.add(btnSalvar);
        btnSalvar.setBounds(710, 380, 125, 59);

        btnExcluir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanelAreaCadastro.add(btnExcluir);
        btnExcluir.setBounds(430, 380, 125, 59);

        jLabel12.setText("Observações");
        jPanelAreaCadastro.add(jLabel12);
        jLabel12.setBounds(60, 270, 76, 16);

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane2.setViewportView(txtObs);

        jPanelAreaCadastro.add(jScrollPane2);
        jScrollPane2.setBounds(150, 240, 794, 110);

        txtNome.setToolTipText("");
        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });
        jPanelAreaCadastro.add(txtNome);
        txtNome.setBounds(153, 54, 330, 24);

        btnNovo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanelAreaCadastro.add(btnNovo);
        btnNovo.setBounds(280, 380, 125, 59);

        btnAlterar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanelAreaCadastro.add(btnAlterar);
        btnAlterar.setBounds(570, 380, 125, 59);

        lblObrigatorioNome.setForeground(new java.awt.Color(255, 0, 0));
        jPanelAreaCadastro.add(lblObrigatorioNome);
        lblObrigatorioNome.setBounds(490, 50, 120, 30);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });
        jPanelAreaCadastro.add(txtCep);
        txtCep.setBounds(150, 100, 150, 20);

        try {
            txtTel_residencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelAreaCadastro.add(txtTel_residencial);
        txtTel_residencial.setBounds(460, 100, 207, 20);

        try {
            txtTel_comercial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelAreaCadastro.add(txtTel_comercial);
        txtTel_comercial.setBounds(740, 100, 200, 20);

        btnBuscaCep.setText("Pesquisar");
        btnBuscaCep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscaCepMouseClicked(evt);
            }
        });
        jPanelAreaCadastro.add(btnBuscaCep);
        btnBuscaCep.setBounds(310, 100, 90, 20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanelAreaCadastro.add(jPanel1);
        jPanel1.setBounds(156, 70, 80, 28);

        jLabel1.setText("Nome");
        jPanelAreaCadastro.add(jLabel1);
        jLabel1.setBounds(102, 58, 33, 16);

        jLabel13.setText("Cód.:");
        jPanelAreaCadastro.add(jLabel13);
        jLabel13.setBounds(110, 20, 28, 16);

        txtCod.setToolTipText("");
        txtCod.setEnabled(false);
        jPanelAreaCadastro.add(txtCod);
        txtCod.setBounds(153, 12, 55, 24);

        txtNumero.setToolTipText("");
        jPanelAreaCadastro.add(txtNumero);
        txtNumero.setBounds(750, 140, 90, 24);

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAreaCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAreaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelDeAbas.addTab("Cadastro", jPanelCadastro);

        tabelaContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "E-mail", "Sexo", "Tipo", "Endereço", "Número", "Bairro", "Cidade", "Estado", "CEP", "Tel. Residêncial", "Tel. Comercial", "Observações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaContatos.getTableHeader().setReorderingAllowed(false);
        tabelaContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaContatos);

        javax.swing.GroupLayout jPanelAreaConsultaLayout = new javax.swing.GroupLayout(jPanelAreaConsulta);
        jPanelAreaConsulta.setLayout(jPanelAreaConsultaLayout);
        jPanelAreaConsultaLayout.setHorizontalGroup(
            jPanelAreaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        jPanelAreaConsultaLayout.setVerticalGroup(
            jPanelAreaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAreaConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        txtConsultaBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaBuscarKeyPressed(evt);
            }
        });

        jLabel14.setText("Digite para buscar");

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAreaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsultaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(2, 2, 2)
                .addComponent(txtConsultaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAreaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelDeAbas.addTab("Consulta", jPanelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelDeAbas))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelDeAbas)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void tabelaContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaContatosMouseClicked
        PainelDeAbas.setSelectedIndex(0);

        txtCod.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 0).toString());
        txtNome.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 1).toString());
        txtEmail.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 2).toString());
        comboSexo.setSelectedItem(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 3).toString());
        txtLogradouro.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 4).toString());
        txtNomeRua.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 5).toString());
        txtNumero.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 6).toString());
        txtBairro.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 7).toString());
        txtCidade.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 8).toString());
        comboEstado.setSelectedItem(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 9).toString());
        txtCep.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 10).toString());
        txtTel_residencial.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 11).toString());
        txtTel_comercial.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 12).toString());
        txtObs.setText(tabelaContatos.getValueAt(tabelaContatos.getSelectedRow(), 13).toString());

    }//GEN-LAST:event_tabelaContatosMouseClicked

    private void txtConsultaBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaBuscarKeyPressed

        String nome = "%" + txtConsultaBuscar.getText() + "%";

        ContatoDao contatoDaoJDBC = DaoFactory.createContatoDao();
        List<Contato> contatos = contatoDaoJDBC.findByName(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaContatos.getModel();

        dados.setNumRows(0);

        contatos.stream().forEach((c) -> {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getSexo(),
                c.getLogradouro(),
                c.getNome_rua(),
                c.getNumero(),
                c.getBairro(),
                c.getCidade(),
                c.getEstado(),
                c.getCep(),
                c.getTel_residencial(),
                c.getTel_comercial(),
                c.getObservacoes()
            });
        });

    }//GEN-LAST:event_txtConsultaBuscarKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void PainelDeAbasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelDeAbasMouseClicked
        lblObrigatorioNome.setText(null);

    }//GEN-LAST:event_PainelDeAbasMouseClicked

    private void jPanelAreaCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreaCadastroMouseClicked

    }//GEN-LAST:event_jPanelAreaCadastroMouseClicked

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            Contato obj = new Contato();

            obj.setId(Integer.parseInt(txtCod.getText()));
            obj.setNome(txtNome.getText());
            obj.setEmail(txtEmail.getText());
            obj.setSexo(Sexo.valueOf(comboSexo.getSelectedItem().toString()));
            obj.setObservacoes(txtObs.getText());
            obj.setLogradouro(txtLogradouro.getText());
            obj.setNome_rua(txtNomeRua.getText());
            obj.setNumero(txtNumero.getText());
            obj.setBairro(txtBairro.getText());
            obj.setCidade(txtCidade.getText());
            obj.setEstado(comboEstado.getSelectedItem().toString());
            obj.setCep(txtCep.getText());
            obj.setTel_residencial(txtTel_residencial.getText());
            obj.setTel_comercial(txtTel_comercial.getText());

            ContatoDao contatoDaoJDBC = DaoFactory.createContatoDao();

            if (obj.getNome().length() == 0) {
                lblObrigatorioNome.setText("*Campo Obrigatório");
            } else {
                contatoDaoJDBC.update(obj);
                JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso.");
            }

        } catch (HeadlessException | NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Por favor selecione um contato para alterar.");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        new LimpaTela().LimpaTela(jPanelAreaCadastro);
        txtObs.setText(" ");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        try {

            ContatoDao contatoDaoJDBC = DaoFactory.createContatoDao();

            int input = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o contato selecionado?", "Atenção", JOptionPane.OK_CANCEL_OPTION);
            if (input == 0) {
                contatoDaoJDBC.deleteById(Integer.parseInt(txtCod.getText()));
                JOptionPane.showMessageDialog(null, "Registro Excluido com sucesso");
                new LimpaTela().LimpaTela(jPanelAreaCadastro);
                txtObs.setText(" ");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um cliente");
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {

            Contato obj = new Contato();

            obj.setNome(txtNome.getText());
            obj.setEmail(txtEmail.getText());
            obj.setSexo(Sexo.valueOf(comboSexo.getSelectedItem().toString()));
            obj.setObservacoes(txtObs.getText());
            obj.setLogradouro(txtLogradouro.getText());
            obj.setNome_rua(txtNomeRua.getText());
            obj.setNumero(txtNumero.getText());
            obj.setBairro(txtBairro.getText());
            obj.setCidade(txtCidade.getText());
            obj.setEstado(comboEstado.getSelectedItem().toString());
            obj.setCep(txtCep.getText());
            obj.setTel_residencial(txtTel_residencial.getText());
            obj.setTel_comercial(txtTel_comercial.getText());

            ContatoDao contatoDaoJDBC = DaoFactory.createContatoDao();

            if (obj.getNome().length() == 0) {
                lblObrigatorioNome.setText("*Campo Obrigatório");
            } else {
                int input = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja incluir um novo registro?", "Atenção", JOptionPane.OK_CANCEL_OPTION);
                if (input == 0) {
                    contatoDaoJDBC.insert(obj);
                    JOptionPane.showMessageDialog(null, "Registro incluído com sucesso.");
                }
            }
        } catch (HeadlessException erro) {
            JOptionPane.showMessageDialog(null, "Nenhum dado para salvar.");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        lblObrigatorioNome.setText(null);
    }//GEN-LAST:event_txtNomeMouseClicked

    private void btnBuscaCepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscaCepMouseClicked

        Contato obj;
        ContatoDao contatoDaoJDBC = DaoFactory.createContatoDao();
        obj = contatoDaoJDBC.buscaCep(txtCep.getText());

        txtLogradouro.setText(obj.getLogradouro());
        txtNomeRua.setText(obj.getNome_rua());
        txtBairro.setText(obj.getBairro());
        txtCidade.setText(obj.getCidade());
        comboEstado.setSelectedItem(obj.getEstado());
    }//GEN-LAST:event_btnBuscaCepMouseClicked

    private void txtLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogradouroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane PainelDeAbas;
    public javax.swing.JPanel PainelPrincipal;
    public javax.swing.JToggleButton btnAlterar;
    public javax.swing.JButton btnBuscaCep;
    public javax.swing.JToggleButton btnExcluir;
    public javax.swing.JToggleButton btnNovo;
    public javax.swing.JToggleButton btnSalvar;
    public javax.swing.JComboBox<String> comboEstado;
    public javax.swing.JComboBox<String> comboSexo;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanelAreaCadastro;
    public javax.swing.JPanel jPanelAreaConsulta;
    public javax.swing.JPanel jPanelCadastro;
    public javax.swing.JPanel jPanelConsulta;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel jTitulo;
    public javax.swing.JLabel lblObrigatorioNome;
    public javax.swing.JTable tabelaContatos;
    public javax.swing.JTextField txtBairro;
    public javax.swing.JFormattedTextField txtCep;
    public javax.swing.JTextField txtCidade;
    public javax.swing.JTextField txtCod;
    public javax.swing.JTextField txtConsultaBuscar;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtLogradouro;
    public javax.swing.JTextField txtNome;
    public javax.swing.JTextField txtNomeRua;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JTextArea txtObs;
    public javax.swing.JFormattedTextField txtTel_comercial;
    public javax.swing.JFormattedTextField txtTel_residencial;
    // End of variables declaration//GEN-END:variables

//Metodo listar na tabela
    public void listar() {
        ContatoDao contatoDaoJDBC = DaoFactory.createContatoDao();
        List<Contato> contatos = contatoDaoJDBC.findAll();
        DefaultTableModel dados = (DefaultTableModel) tabelaContatos.getModel();

        dados.setNumRows(0);

        contatos.stream().forEach((c) -> {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getSexo(),
                c.getLogradouro(),
                c.getNome_rua(),
                c.getNumero(),
                c.getBairro(),
                c.getCidade(),
                c.getEstado(),
                c.getCep(),
                c.getTel_residencial(),
                c.getTel_comercial(),
                c.getObservacoes()
            });
        });

    }
}
